SocialManager/Models/FacebookPhotoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using SocialManager.Attributes;

namespace SocialManager.Models
{
    public class FacebookPhotoViewModel
    {
        [Required]
        [FacebookMapping("id")]
        public string Id { get; set; }

        [Display(Name = "Name")]
        [FacebookMapping("name")]
        public string name { get; set; }

        [FacebookMapping("picture")]
        public string SmallPicture { get; set; }

        [FacebookMapping("source", parent = "images")]
        public string LargePicture { get; set; }

    }
}

SocialManager/Controllers/FacebookPhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialManager.Models;
using SocialManager.Extensions;
using Facebook;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Configuration;
using Newtonsoft.Json;
using SocialManager.Filters;
using System.Dynamic;

namespace SocialManager.Controllers
{
    [Authorize]
    public class FacebookPhotoController : BaseController
    {
        protected override Dictionary<string, FacebookPermissionRequest> GetRequiredPermissions()
        {
            var RequiredPermissions =
                new Dictionary<string, FacebookPermissionRequest> { 
                { "publish_actions", 
                    new FacebookPermissionRequest { 
                        name = "Posting", 
                        description = "Provides the Social Manager with ability to create new albums and photos.", 
                        permision_scope_value = "publish_actions", 
                        requested = false } },
                { "user_photos", 
                    new FacebookPermissionRequest { 
                        name = "Photo Access", 
                        description = "Provides the Social Manager with ability to view and create albums and photos.", 
                        permision_scope_value = "user_photos", 
                        requested = false } }
               };

            return RequiredPermissions;

        }

        // GET: FacebookPhoto
        [FacebookCheckPermission]
        public ActionResult Index()
        {
            return View();
        }
        
        #region Albums Actions
        [HttpPost]
        public async Task<ActionResult> GetAlbums()
        {
            #region Facebook Graph API Retrieve Albums
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();
                var fb = new FacebookClient(access_token);

                #region Get Photo Albums
                dynamic myInfo = await fb.GetTaskAsync(
                        string.Format("me/albums?fields=id,name, count, link," +
                                      "picture, privacy")
                        .GraphAPICall(appsecret_proof), null);
                #endregion

                #region Hydrate results
                //Hydrate FacebookProfileViewModel with Graph API results
                var albumList = new List<FacebookAlbumViewModel>();
                foreach (dynamic album in myInfo.data)
                {
                    albumList.Add(DynamicExtension.ToStatic<FacebookAlbumViewModel>(album));
                }
                #endregion
                return PartialView("FB_GetAlbums_Response", albumList);
            }
            else
                throw new HttpException(404, "Missing Access Token");
            #endregion
        }

        [HttpPost]
        public async Task<ActionResult> CreateAlbum(string NewAlbumName, string Privacy)
        {
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();
                var fb = new FacebookClient(access_token);

                #region Get Photo Albums
                dynamic myInfo = await fb.PostTaskAsync(
                        (string.Format("me/albums?name={0}",
                        NewAlbumName) +
                        "&privacy={{'value':'" + Privacy + "'}}")
                        .GraphAPICall(appsecret_proof), null);
                #endregion

                return null; //on success event formNewAlbum ajax form handles redirecting to the index view
                             //This could return the new album id that we get back from Facebook's graph api
                             //If the new album id is needed for your implementation
            }
            else
                throw new HttpException(404, "Missing Access Token");
        }

        [HttpPost]
        public async Task<ActionResult> ReloadAlbum(string ReloadAlbumId)
        {

            #region Facebook Graph API Retrieve Albums
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();
                var fb = new FacebookClient(access_token);

                #region Get Photo Albums
                dynamic myInfo = await fb.GetTaskAsync(
                        string.Format(
                        "me/albums/{0}?fields=id,name,count,link,can_upload, picture, privacy",
                        ReloadAlbumId)
                        .GraphAPICall(appsecret_proof), null);
                #endregion

                #region Hydrate results
                //Hydrate FacebookProfileViewModel with Graph API results
                FacebookAlbumViewModel album = DynamicExtension.ToStatic<FacebookAlbumViewModel>
                    (myInfo.data[0]);
                #endregion

                return PartialView("FB_Album_Response", album);

            }
            else
                throw new HttpException(404, "Missing Access Token");
            #endregion
        }

        #endregion

        #region Photo Actions
        [HttpPost]
        public async Task<ActionResult> GetPhotos(
                    string AlbumId)
        {
            #region Facebook Graph API Retrieve Albums
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                if (!string.IsNullOrEmpty(AlbumId))
                {
                    var appsecret_proof = access_token.GenerateAppSecretProof();
                    var fb = new FacebookClient(access_token);

                    #region Get Photo Albums
                    dynamic PhotoResults = await fb.GetTaskAsync(
                            (string.Format("{0}/photos", AlbumId)
                            + "?fields=id,picture,name,images{{source}}&limit=25")
                            .GraphAPICall(appsecret_proof));
                    #endregion

                    #region Results
                    var photoList = HydratePhotoList(PhotoResults);
                    ViewBag.ShowGetMoreData = GetMoreDataQuery(PhotoResults, access_token);
                    #endregion

                    return PartialView("FB_GetPhotos_Response", photoList);
                }
                else
                    throw new HttpException(404, "Missing Current Album Id");

            }
            else
                throw new HttpException(404, "Missing Access Token");
            #endregion
        }

        [HttpPost]
        public async Task<ActionResult> GetMorePhotos(string NextPageUri)
        {
            if (!string.IsNullOrEmpty(NextPageUri))
            {


                #region Get More Paged Data
                var access_token = HttpContext.Items["access_token"].ToString();
                if (!string.IsNullOrEmpty(access_token))
                {
                    var appsecret_proof = access_token.GenerateAppSecretProof();
                    var fb = new FacebookClient(access_token);
                    dynamic nextPageResult = await fb.GetTaskAsync(NextPageUri.GraphAPICall(appsecret_proof));

                    #region Results
                    var photoList = HydratePhotoList(nextPageResult);
                    ViewBag.ShowGetMoreData = GetMoreDataQuery(nextPageResult, access_token);
                    #endregion

                    return PartialView("FB_GetPhotos_Response", photoList);
                }
                else
                    throw new HttpException(404, "Missing Access Token");
                #endregion
            }
            else
                return null;
        }


        [HttpPost]
        public async Task<JsonResult> PostVideo(IEnumerable<HttpPostedFileBase> VideosToUpload,
                                                  string VideoDescription)
        {
            var access_token = HttpContext.Items["access_token"].ToString();
            //Get Upload Photo Data
            var UploadedVideo = VideosToUpload.First();
            var video_FBObject = new Facebook.FacebookMediaStream
            {
                FileName = UploadedVideo.FileName,
                ContentType = UploadedVideo.ContentType
            };
            video_FBObject.SetValue(UploadedVideo.InputStream);

            //FB Graph API Parameters
            dynamic parameters = new ExpandoObject();
            parameters.access_token = access_token;
            //If you have enabled requires app secret proof on FB app dashboard for your registerted application
            //parameters.appsecret_proof = access_token.GenerateAppSecretProof();
            parameters.source = video_FBObject;
            if (!string.IsNullOrEmpty(VideoDescription))
                parameters.message = VideoDescription;

            //region FB Graph API Add Photo
            var fb = new FacebookClient();
            dynamic result = await fb.PostTaskAsync(
                  "/me/videos", parameters);

            #region Add Photo Result
            if (result != null &&
                result.id != null)
                if (result.post_id != null)
                    return Json(new { status = "posted" });
                else
                    return Json(new { status = "pending" });
            else
                return Json(new { status = "failed" });
            #endregion

           
        }

        [HttpPost]
        public async Task<JsonResult> PostPhoto(IEnumerable<HttpPostedFileBase> PhotosToUpload,

SocialManager/Views/FacebookPhoto/AjaxForms/AddPhoto.cshtml
@using (Ajax.BeginForm("PostVideo", "FacebookPhoto",
            null,
            new
            {
                enctype = "multipart/form-data",
                id = "formPhotoUpload"
            }))
{
    <div id="divLoadingPhotos"
         style="display:none; z-index:1000; position:absolute;
                     top:50%; left:50%; opacity:0.85;
                    -moz-opacity:0.85; filter:alpha(opacity=85); ">
        <img src="~/images/loader.gif" />
    </div>
    <div class="form-group">
        <input id="TargetAlbumId" name="TargetAlbumId" type="hidden" />
        <textarea name="PhotoDescription"
                  id="PhotoDescription"
                  class="form-control"
                  rows="2"
                  style="max-width:100%;"
                  placeholder="New Photo Description"></textarea>
        <div class="input-group">
            @*Utilizing Twitter Bootstrap stylized file upload buttons
            Created By: Cory LaViska
            Article: Whipping File Inputs Into Shape with Bootstrap 3
            reference: 
                http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/*@  
            <span class="input-group-btn">
                <span class="btn btn-primary btn-file">
                    Browse&hellip; <input type="file" 
                                          name="PhotosToUpload" 
                                          id="PhotosToUpload" />
                </span>
            </span>
            <input type="text" class="form-control" readonly />
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit" 
                        id="SubmitPhoto"
                        name="SubmitPhoto">Add Photo</button>
            </span>
        </div>
    </div>

}

SocialManager/Views/FacebookPhoto/AjaxForms/AlbumList.cshtml
@using (Ajax.BeginForm("GetAlbums", "FacebookPhoto",
            null,
            new
            {
                id = "formGetAlbums"
            }))
{
    <div id="divLoadingAlbums"
         style="display:none; z-index:1000; position:absolute;
                top:50%; left:50%; opacity:0.85;
            -moz-opacity:0.85; filter:alpha(opacity=85); ">
        <img src="~/images/loader.gif" />
    </div>
    <div id="Albums_Result">
    </div>
}

SocialManager/Views/FacebookPhoto/AjaxForms/AlbumReload.cshtml
@using (Ajax.BeginForm("ReloadAlbum", "FacebookPhoto",
            null,
            new
            {
                id = "formReloadAlbum"
            }))
{
    <input type="hidden" id="ReloadAlbumId" />
}

SocialManager/Views/FacebookPhoto/AjaxForms/CreateAlbum.cshtml
@using (Ajax.BeginForm("CreateAlbum", "FacebookPhoto",
                    null,
                    new
                    {
                        id = "formNewAlbum"
                    }))
{
    <div class="form-group">
        <textarea name="NewAlbumName" id="NewAlbumName"
               class="form-control"
               rows="2"
               placeholder="New Album Name"></textarea>
        <input name="Privacy" type="hidden" value="EVERYONE" />
        <div class="btn-group">
            <button id="dropdownMenuPermission"
                    class="btn dropdown-toggle btn-info"
                    data-toggle="dropdown"
                    type="button">
                Public
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="#"
                       data-privacy="EVERYONE">Public</a>
                </li>
                <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="#"
                       data-privacy="ALL_FRIENDS">All Friends</a>
                </li>
                <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="#"
                       data-privacy="FRIENDS_OF_FRIENDS">Friends of Friends</a>
                </li>
                <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="#"
                       data-privacy="SELF">Only Me</a>
                </li>
            </ul>
        </div>
        <button type="submit" class="btn btn-primary">
            Add Album
        </button>
    </div>
}

SocialManager/Views/FacebookPhoto/AjaxForms/PhotoList.cshtml
@using (Ajax.BeginForm("GetPhotos", "FacebookPhoto",
                            null,
                            new
                            {
                                id = "Photo_Results_Form"
                            }))
{
    <input id="AlbumId" name="AlbumId" type="hidden" />
    <div class="panel panel-default">
        <div class="panel-body">
            <label id="ShowingCountLabel"
                   class="text-success">
            </label>
            <div id="FB_Scrollable_List"
                 class="table-responsive bodycontainer scrollable">
                <div id="Photo_Results"></div>
                <div id="More_FB_Photos"></div>
            </div>
        </div>
    </div>
}