SocialManager/Models/FacebookSubscriptionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using SocialManager.Attributes;

namespace SocialManager.Models
{
    public class FacebookSubscriptionViewModel
    {

        [FacebookMapping("object")]
        public string Type { get; set; }

        [FacebookMapping("callback_url")]
        public string callback_url { get; set; }

        [FacebookMapping("active")]
        public bool active { get; set; }

        [FacebookMapping("fields")]
        public dynamic fields { get; set; }
    }
}

SocialManager/Controllers/FacebookSubscriptionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Serialization;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Dynamic;
using Facebook;
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;
using SocialManager.Models;
using SocialManager.Extensions;

namespace SocialManager.Controllers
{
    [System.Web.Mvc.Authorize]
    public class FacebookSubscriptionController : BaseController
    {
        [HttpGet]
        [ActionName("Index")]
        [AllowAnonymous]
        public ResponseActionResult ValidateSubscription()
        {                    
            string hubMode = Request.QueryString["hub.mode"];
            string hubVerifyToken = Request.QueryString["hub.verify_token"];
            string hubChallenge = Request.QueryString["hub.challenge"];

            Facebook.FacebookClient fb = new FacebookClient();
            fb.SubscriptionVerifyToken = 
                ConfigurationManager.AppSettings["Facebook_Verify_Token"];
            // VerifyGetSubscription will throw exception if verification fails.
            fb.VerifyGetSubscription(hubMode,
                                     hubVerifyToken,
                                     hubChallenge);
            string message = string.Format("Subscription Verification Received - {0}",
                        hubVerifyToken);

            #region Broadcast Message
                GlobalHost.ConnectionManager.GetHubContext<NotificationHub>().
                    Clients.All.
                    addNewNotificationToPage(
                             RenderRazorViewToString("FB_NotificationItem",
                             NotificationMessage.NewMessage("Subscription", message))
                    );
            #endregion
 
            return new ResponseActionResult(hubChallenge);
        }

        [HttpPost]
        [ActionName("Index")]
        [AllowAnonymous]
        public HttpStatusCodeResult ReceiveNotification()
        {
                Facebook.FacebookClient fb = new FacebookClient();
                fb.SetJsonSerializers(null, Deserializer);
                // VerifyPostSubscription will throw exception if verification fails.
                // result is a json object that was sent by Facebook                
                FacebookNotifyViewModel notification = 
                    (FacebookNotifyViewModel)fb.VerifyPostSubscription(
                                    Request.Headers["X-Hub-Signature"],
                                    new StreamReader(Request.InputStream).ReadToEnd(),
                                    typeof(FacebookNotifyViewModel),
                                    ConfigurationManager.AppSettings["Facebook_AppSecret"]);
                #region Broadcast notification         
                GlobalHost.ConnectionManager.GetHubContext<NotificationHub>().
                    Clients.All.
                    addNewNotificationToPage(
                                RenderRazorViewToString("FB_NotificationItem", notification)
                    );
                if (notification.Object == "page")
                {
                    GlobalHost.ConnectionManager.GetHubContext<NotificationHub>().
                        Clients.All.
                        FBPageNotification(notification.entry.First().id);
                }

                #endregion

                return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        private FacebookNotifyViewModel Deserializer(string input, Type deserializerType)
        {
            return JsonConvert.DeserializeObject<FacebookNotifyViewModel>(input);
        }

        public ActionResult Manage()
        {

            FacebookAddSubscriptionViewModel notificationmodel = 
                new FacebookAddSubscriptionViewModel(
                                    GetUserSubscriptionFields(),
                                    GetPageSubscriptionFields(),
                                    GetPermissionsSubscriptionFields()
                                    );
            return View(notificationmodel);
        }
 
        [HttpGet]
        public async Task<ActionResult> Get()
        {
            #region Facebook Graph API Retrieve Subscriptions
            var app_token = base.GetAppToken;
            if (!string.IsNullOrEmpty(app_token))
            {
                var fb = new FacebookClient(app_token);
                #region Get Subscriptions
                dynamic result = await fb.GetTaskAsync(
                        string.Format("subscriptions"), null);
                #endregion

                #region Hydrate results
                //Hydrate FacebookSubscriptionViewModel with Graph API results
                var subscriptionList = new List<FacebookSubscriptionViewModel>();
                foreach (dynamic subscription in result.data)
                {
                    subscriptionList.Add(
                        DynamicExtension.ToStatic<FacebookSubscriptionViewModel>(subscription));
                }
                #endregion
                return PartialView("FB_GetSubscriptions_Response", subscriptionList);
            }
            else
                throw new HttpException(404, "Missing App Token");
            #endregion
        }

        [HttpPost]
        public async Task<JsonResult> Add(string subscription, string[] SubscriptionField)
        {
            #region Facebook Graph API Retrieve Subscriptions
            var app_token = GetAppToken;
            if (!string.IsNullOrEmpty(app_token))
            {
                var fb = new FacebookClient(app_token);
                #region Get Subscriptions
                dynamic result = await fb.PostTaskAsync(
                        string.Format("subscriptions?object={0}&callback_url={1}&"+
                                      "verify_token={2}&fields={3}",
                        subscription,
                        ConfigurationManager.AppSettings["Facebook_Subscription_Callback"],
                        ConfigurationManager.AppSettings["Facebook_Verify_Token"],
                        Server.UrlEncode(String.Join(",", SubscriptionField))), 
                        null);
                #endregion

                 return Json(result);
            }
            else
                throw new HttpException(404, "Missing App Token");
            #endregion
        }

        [HttpPost]
        public async Task<JsonResult> Delete(string subscription_to_delete)
        {
            #region Facebook Graph API Retrieve Subscriptions
            var app_token = GetAppToken;
            if (!string.IsNullOrEmpty(app_token))
            {
                var fb = new FacebookClient(app_token);
                #region Delete Subscription
                dynamic result = await fb.DeleteTaskAsync(
                        string.Format("subscriptions?object={0}", 
                        subscription_to_delete));
                #endregion

                return Json(result);
            }
            else
                throw new HttpException(404, "Missing App Token");
            #endregion       
        }
        private string[] GetUserSubscriptionFields()
        {
            return new string[]{"about",
                                "about_me",
                                "activities",
                                "allowed_restrictions",
                                "birthday",
                                "birthday_date",
                                "books",
                                "checkin_deal_claims",
                                "contact_email",
                                "current_location",
                                "education",
                                "education_history",
                                "email",
                                "email_hashes",
                                "events",
                                "family",
                                "feed",
                                "first_name",
                                "friend_request",
                                "has_added_app",
                                "hometown",
                                "hometown_location",
                                "hs_info",
                                "interests",
                                "is_app_user",
                                "is_blocked",
                                "last_name",
                                "likes",
                                "link",
                                "locale",
                                "location",
                                "meeting_for",
                                "meeting_sex",
                                "movies",
                                "music",
                                "name",
                                "notes_count",
                                "online_presence",
                                "photos",
                                "pic",
                                "picture",
                                "pic_https",
                                "pic_with_logo",
                                "pic_big",
                                "pic_big_https",
                                "pic_big_with_logo",
                                "pic_small",
                                "pic_small_https",
                                "pic_small_with_logo",
                                "pic_square",
                                "pic_square_https",
                                "pic_square_with_logo",
                                "political_views",
                                "profile_blurb",
                                "profile_update_time",
                                "profile_url",
                                "proxied_email",
                                "quotes",

SocialManager/Views/FacebookSubscription/AjaxForms/AddSubscription.cshtml
@using (Ajax.BeginForm("Add", "FacebookSubscription", null,
                new AjaxOptions
                {
                    OnFailure = "handleError(xhr,'ErrorMessageDiv')",
                    HttpMethod = "Post",
                    LoadingElementId = "divWaitImage",
                    OnSuccess = "AddSubscriptionHandler(xhr)"
                },
                new
                {
                    id = "Add_Subscription_Form",
                    @class = "form",role = "form"
                }))
{
    <div id="divWaitImage" style="display:none;" class="text-center">
        <img src="~/images/loader.gif" />
    </div>
    <div class="well">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group input-group">
                    <div class="input-group">
                        <div class="btn-group">
                            <button id="dropdownMenuSubscription"
                                    class="btn dropdown-toggle"
                                    data-toggle="dropdown"
                                    type="button">
                                User
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" href="#"
                                       data-subscription="user">User</a>
                                </li>
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" href="#"
                                       data-subscription="page">Page</a>
                                </li>
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" href="#"
                                       data-subscription="permissions">Permissions</a>
                                </li>
                            </ul>
                        </div>
                        <input name="subscription" type="hidden" value="user" />
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <h6 class="text-center text-muted" id="SubscriptionFieldListTitle"></h6>
            <div class="col-md-12 bodycontainer scrollable" id="SubscriptionFieldList"></div>
        </div>
    </div>
}

SocialManager/Views/FacebookSubscription/AjaxForms/DeleteSubscription.cshtml
@using (Ajax.BeginForm("Delete", "FacebookSubscription", null,
                        new AjaxOptions
                        {
                            OnFailure = "handleError(xhr,'ErrorMessageDiv')",
                            HttpMethod = "Post",
                            LoadingElementId = "divWaitImage_Subscriptions",
                            OnSuccess = "$('#Get_Subscriptions_Form').submit()"
                        },
                        new
                        {
                            id = "Delete_Subscriptions_Form",
                            @class = "form",
                            role = "form"
                        }))
{
    <input name="subscription_to_delete" type="hidden" />
}

SocialManager/Views/FacebookSubscription/AjaxForms/GetSubscription.cshtml
@using (Ajax.BeginForm("Get", "FacebookSubscription", null,
                        new AjaxOptions
                        {
                            OnFailure = "handleError(xhr,'ErrorMessageDiv')",
                            HttpMethod = "Get",
                            UpdateTargetId = "Subscription_ResponseDiv",
                            LoadingElementId = "divWaitImage_Subscriptions",
                            InsertionMode = InsertionMode.Replace
                        },
                        new
                        {
                            id = "Get_Subscriptions_Form",
                            @class = "form",
                            role = "form"
                        }))
{
    <div id="divWaitImage_Subscriptions" style="display:none;" class="text-center">
        <img src="~/images/loader.gif" />
    </div>
    <div id="Subscription_ResponseDiv"></div>
}