SocialManager/Controllers/FacebookSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialManager.Models;
using SocialManager.Extensions;
using Facebook;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Configuration;
using Newtonsoft.Json;
using SocialManager.Filters;

namespace SocialManager.Controllers
{
    [Authorize]
    public class FacebookSearchController : BaseController
    {
        // GET: FacebookSearch
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [FacebookCheckPermission]
        public async Task<ActionResult> Find(
            string QueryValue,
            string SearchBy,
            string SearchCenterCoordinates)
        {
            #region Permission Check
            PermissionRequestViewModel permissionViewModel = base.GetMissingPermissions();
            if (permissionViewModel != null &&
                permissionViewModel.MissingPermissions.Count > 0)
            {
                return View("FB_RequestPermission", permissionViewModel);
            }
            #endregion

            #region Facebook Graph API Search call
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();
                var fb = new FacebookClient(access_token);

                #region Search For Place
                string _searchCenterParam = string.Empty;
                if (SearchBy == "place" &&
                    !string.IsNullOrEmpty(SearchCenterCoordinates))
                    _searchCenterParam = string.Format("&center={0}&distance={1}",
                        SearchCenterCoordinates,
                        ConfigurationManager.AppSettings["Facebook_Distance_Meters"].ToString());
                #endregion

                #region Search Facebook Graph Query call
                dynamic myInfo = await fb.GetTaskAsync(
                    (string.Format("search?q={0}&type={1}{2}&limit=50",
                                    QueryValue,
                                    SearchBy,
                                    _searchCenterParam) +
                        "&fields=name,id,picture.type(large).width(100).height(100){{url}}")
                        .GraphAPICall(appsecret_proof));
                #endregion

                #region Hydrate results
                //Hydrate FacebookProfileViewModel with Graph API results
                var userList = new List<FacebookFriendViewModel>();
                foreach (dynamic friend in myInfo.data)
                {

                    userList.Add(DynamicExtension.ToStatic<FacebookFriendViewModel>(friend));
                }
                

                #endregion

                #region Paging Results
                string NextPageURI = string.Empty;

                if (myInfo.paging != null &&
                    myInfo.paging.next != null)
                    NextPageURI = myInfo.paging.next;

                ViewBag.ShowGetMoreData = GetNextPageQuery(NextPageURI, access_token);
                #endregion

                return PartialView("FindResults", userList);

            }
            else
                throw new HttpException(404, "Missing Access Token");
            #endregion
        }
       
        
        [HttpPost]
        [FacebookCheckPermission]
        public async Task<ActionResult> GetMoreData(string NextPageUri)
        {
            if (!string.IsNullOrEmpty(NextPageUri))
            {
                #region Permission Check
                PermissionRequestViewModel permissionViewModel = base.GetMissingPermissions();
                if (permissionViewModel != null &&
                    permissionViewModel.MissingPermissions.Count > 0)
                {
                    return View("FB_RequestPermission", permissionViewModel);
                }
                #endregion

                #region Get More Paged Data
                var access_token = HttpContext.Items["access_token"].ToString();
                if (!string.IsNullOrEmpty(access_token))
                {
                    var appsecret_proof = access_token.GenerateAppSecretProof();
                    var fb = new FacebookClient(access_token);
                    dynamic nextPageResult = await fb.GetTaskAsync(NextPageUri.GraphAPICall(appsecret_proof));

                    #region Hydrate results
                    //Hydrate FacebookProfileViewModel with Graph API results
                    var userList = new List<FacebookFriendViewModel>();
                    foreach (dynamic friend in nextPageResult.data)
                    {

                        userList.Add(DynamicExtension.ToStatic<FacebookFriendViewModel>(friend));
                    }


                    #endregion

                    #region Paging Results
                    string NextPageURI = string.Empty;

                    if (nextPageResult.paging != null &&
                        nextPageResult.paging.next != null)
                        NextPageURI = nextPageResult.paging.next;

                    ViewBag.ShowGetMoreData = GetNextPageQuery(NextPageURI, access_token);
                    #endregion

                    return PartialView("FindResults", userList);
                }
                else
                    throw new HttpException(404, "Missing Access Token");
                #endregion
            }
            else
                return null;
        }

        [HttpPost]
        public ActionResult GeoCode(string LocationSearch)
        {

            WebRequest request = WebRequest.Create(string.Format(
                "http://dev.virtualearth.net/REST/v1/Locations?query={0}&output=json&key={1}",
                Server.UrlEncode(LocationSearch),
                ConfigurationManager.AppSettings["BingMapKey"].ToString()));
            request.Method = WebRequestMethods.Http.Get;

            WebResponse response = request.GetResponse();

            StreamReader sr = new StreamReader(response.GetResponseStream());
            string _recievBuffer = sr.ReadToEnd();
            dynamic geocodeResults = JsonConvert.DeserializeObject(_recievBuffer);

            #region Hydrate Results
            if (geocodeResults != null &&
                geocodeResults.resourceSets != null &&
                geocodeResults.resourceSets[0] != null &&
                geocodeResults.resourceSets[0].resources != null)
            {
                //Hydrate GeoCodeLocationViewModel with Geo Code results
                var locationList = new List<GeoCodeLocationViewModel>();
                foreach (dynamic resource in geocodeResults.resourceSets[0].resources)
                {
                    locationList.Add(new GeoCodeLocationViewModel()
                    {
                        Name = resource.name.Value,
                        Coordinates = string.Format("{0},{1}",
                        resource.point.coordinates[0].ToString(),
                        resource.point.coordinates[1].ToString())
                    });
                }
            #endregion
                return PartialView("GeoCodeResults", locationList);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid GeoCode Request");

        }

        protected override Dictionary<string, FacebookPermissionRequest> GetRequiredPermissions()
        {
            Dictionary<string, FacebookPermissionRequest> RequiredPermissions =
                new Dictionary<string, FacebookPermissionRequest>();

            RequiredPermissions.Add
            ("public_profile",
                    new FacebookPermissionRequest
                    {
                        name = "Basic Searching",
                        description = "Provides the Social Manager with ability to search for people, pages, events, groups or places.",
                        permision_scope_value = "public_profile",
                        requested = false
                    }
            );
            return RequiredPermissions;

        }

    }



}

SocialManager/Views/FacebookSearch/FindResults.cshtml
@model IEnumerable<SocialManager.Models.FacebookFriendViewModel>


        <table class="table table-hover table-striped table-condensed">
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <div class="text-center">
                                <a href="http://www.facebook.com/@item.TaggingId" target="_blank">
                                    <img class="img-thumbnail" src="@item.ImageURL" /><br />
                                    <span class="text-primary">@Html.DisplayFor(modelItem => item.Name)</span>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
@if (ViewBag.ShowGetMoreData != null)
{
    <input id="FB_Next_PageLink" type="hidden" value="@ViewBag.ShowGetMoreData" />
}
<input id="FB_CurrentDataCount" type="hidden" value="@Model.Count()" />

SocialManager/Views/FacebookSearch/GeoCodeResults.cshtml
@model IEnumerable<SocialManager.Models.GeoCodeLocationViewModel>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-primary">
            @Html.DisplayNameFor(model => model.Name)
        </div>
    </div>
    @foreach (var item in Model)
    {
        <div class="row table-striped">
            <div class="col-md-12">
                @Html.RadioButton("LocationCenter", item.Name,
                                                                new
                                                                {
                                                                    onclick = "$('#SearchCenterCoordinates').val('" +
                                                                        item.Coordinates + "');"
                                                                })
                @Html.DisplayFor(modelItem => item.Name)<br />
                <span class="text-muted text-right">
                    <small>
                        (@Html.DisplayFor(modelItem => item.Coordinates))
                    </small>
                </span>
            </div>
        </div>
    }
    <div class="row">
        <div class="col-md-12">
            @Model.Count() locations
        </div>
    </div>
</div>
            @*<div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                </tr>
                            </table>
                            <div class="bodycontainer scrollable">
                                <table class="table table-hover table-striped table-condensed table-scrollable">
                                    <tbody>
                                        @{
                                            int idx = 0;
                                        }
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.RadioButton("LocationCenter", item.Name,
                                                                new
                                                                {
                                                                    onclick = "$('#SearchCenterCoordinates').val('" +
                                                                        item.Coordinates + "');"
                                                                })
                                                    @Html.DisplayFor(modelItem => item.Name)<br />
                                                    <span class="text-muted text-right">
                                                        <small>
                                                            (@Html.DisplayFor(modelItem => item.Coordinates))
                                                        </small>
                                                    </span>
                                                </td>
                                            </tr>
                                            idx++;
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <table>
                                <tfoot>
                                    @Model.Count() locations
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>*@

SocialManager/Views/FacebookSearch/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<hr />

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-3">
        @using (Ajax.BeginForm("Find", "FacebookSearch",
                                new AjaxOptions
                                {
                                    OnFailure = "handleError(xhr,'Search_Results')",
                                    HttpMethod = "Post",
                                    UpdateTargetId = "Search_Results",
                                    LoadingElementId = "divLoadingSearch",
                                    OnSuccess = "CompleteLoadingPagedData"
                                },
                                new
                                {
                                    id = "Search_Results_Form"
                                }))
        {
            <div class="input-group text-center">
                <input type="text" class="form-control" placeholder="Search"
                       name="QueryValue" onkeydown="
                                if (event.keyCode == 13)
                                    { return false; }" />
                <div class="input-group-btn">
                    <button class="btn btn-primary dropdown-toggle"
                            data-toggle="dropdown"
                            type="button"
                            onclick="$('#Search_Results').empty();">
                        Search
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right" role="menu">
                        <li><a href="#" onclick="SearchFormSubmitter('For People','user')">For People</a></li>
                        <li><a href="#" onclick="SearchFormSubmitter('For Places','place')">For Places</a></li>
                        <li><a href="#" onclick="SearchFormSubmitter('For Pages','page')">For Pages</a></li>
                        <li><a href="#" onclick="SearchFormSubmitter('For Events','event')">For Events</a></li>
                        <li><a href="#" onclick="SearchFormSubmitter('For Groups','group')">For Groups</a></li>
                    </ul>

                </div>
                <input id="SearchBy" name="SearchBy" type="hidden" readonly />
                <input id="SearchCenterCoordinates" name="SearchCenterCoordinates" type="hidden" readonly />
            </div>
        }
    </div>
    <div class="col-md-2">
        <label id="SearchByLabel" class="text-info"></label>
    </div>
    <div class="col-md-3">
        @using (Ajax.BeginForm("GeoCode", "FacebookSearch",
                            new AjaxOptions
                            {
                                OnFailure = "handleError(xhr,'GeoCode_Results')",
                                HttpMethod = "Post",
                                UpdateTargetId = "GeoCode_Results",
                                LoadingElementId = "divLoadingGeoCode"
                            },
                            new
                            {
                                id = "GeoCode_Results_Form"
                            }))
        {
            <div class="input-group text-center">
                <input type="text" class="form-control" placeholder="Location" name="LocationSearch" 
                       onkeydown="if (event.keyCode == 13) { return false; } " />
                <div class="input-group-btn">
                    <button class="btn btn-primary" onclick="$('#GeoCode_Results').empty();
                        $('#GeoCode_Results_Form').submit(); return false;">Geocode</button>
                </div>
            </div>
        }
    </div>
    <div class="col-md-2"></div>
</div>

<hr />
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-4 text-center">
        <div id="divLoadingSearch" 
             style="display:none; z-index:1000; position:absolute;  
              top:50%; left:50%; opacity:0.85;
              -moz-opacity:0.85; filter:alpha(opacity=85); ">
            <img src="~/images/loader.gif" />
        </div>

        <div id="FB_Scrollable_List" 
             class="table-responsive 
             bodycontainer scrollable">
            <div id="Search_Results"></div>
            <div id="More_FB_Data"></div>
        </div>

        
        <label id="ShowingCountLabel" 
               class="text-success">
        </label>
    </div>
    <div class="col-md-6">
        <div id="divLoadingGeoCode" style="display:none;">
            <img src="~/images/loader.gif" />
        </div>
        <div id="GeoCode_Results"></div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")   
    @Scripts.Render("~/bundles/jqueryajax")
    <script type="text/javascript">

        var AllowGetMoreDataCall = true;
        var ItemShowingCount = 0;

        wireUpContinousScroll(
        "divLoadingSearch",
        "FacebookSearch/GetMoreData",
        "More_FB_Data");

        function SearchFormSubmitter(searchby, searchbyType) {
            $("#SearchBy").val(searchbyType);
            $("#SearchByLabel").html(searchby);
            AllowGetMoreDataCall = false;
            ItemShowingCount = 0;
            $("#FB_Scrollable_List").scrollTop(0);
            $("#More_FB_Data").empty();
            $('#Search_Results_Form').submit();
            return false;
        }

        

        function CompleteLoadingPagedData()
        {
            AllowGetMoreDataCall = true;
            ItemShowingCount = ItemShowingCount + parseInt($("#FB_CurrentDataCount").val());
            $("#ShowingCountLabel").html("Showing " + ItemShowingCount + " items");
        }
    </script>

}