SocialManager/Models/FacebookPostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using SocialManager.Attributes;

namespace SocialManager.Models
{
    public class FacebookPostViewModel
    {
        [Required]
        [FacebookMapping("id")]
        public string Id { get; set; }

        [FacebookMapping("created_time")]
        public DateTime Created_Time { get; set; }

        [FacebookMapping("id", parent = "from")]
        public string From_Id { get; set; }

        [FacebookMapping("name", parent = "from")]
        public string From_Name { get; set; }

        [FacebookMapping("url", parent = "from")]
        public string From_Picture_Url { get; set; }

        [FacebookMapping("story")]
        public string Story { get; set; }

        [FacebookMapping("message")]
        public string Message { get; set; }

        [FacebookMapping("picture")]
        public string Picture_Url { get; set; }

        [FacebookMapping("link")]
        public string Link { get; set; }

        [FacebookMapping("description")]
        public string Description { get; set; }

        [FacebookMapping("caption")]
        public string Caption { get; set; }

        [FacebookMapping("type")]
        public string Type { get; set; }

        [FacebookMapping("likes")]
        public dynamic Likes { get; set; }

        [FacebookMapping("comments")]
        public dynamic Comments { get; set; }

    }
}

SocialManager/Controllers/FacebookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;
using Facebook;
using SocialManager.Models;
using SocialManager.Extensions;
using SocialManager.Filters;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Security.Claims;
using System.Configuration;

namespace SocialManager.Controllers
{
    [Authorize]
    public class FacebookController : BaseController
    {
        // GET: Facebook
        [FacebookCheckPermission]
        public async Task<ActionResult> Index()
        {
                #region Permission Check
                PermissionRequestViewModel permissionViewModel = base.GetMissingPermissions();
                if (permissionViewModel != null &&
                    permissionViewModel.MissingPermissions.Count > 0)
                {
                    return View("FB_RequestPermission", permissionViewModel);
                }
                #endregion
                var access_token = HttpContext.Items["access_token"].ToString();
                if (!string.IsNullOrEmpty(access_token))
                {
                    var appsecret_proof = access_token.GenerateAppSecretProof();
                    var fb = new FacebookClient(access_token);

                    //Get current user's profile
                    dynamic myInfo = await fb.GetTaskAsync("me?fields=first_name,last_name,link,locale,email,name,birthday,gender,location,bio,age_range".GraphAPICall(appsecret_proof));

                    //get current picture
                    dynamic profileImgResult = await fb.GetTaskAsync("{0}/picture?width=100&height=100&redirect=false".GraphAPICall((string)myInfo.id, appsecret_proof));

                    //Hydrate FacebookProfileViewModel with Graph API results
                    var facebookProfile = DynamicExtension.ToStatic<FacebookProfileViewModel>(myInfo);
                    facebookProfile.ImageURL = profileImgResult.data.url;
                    return View(facebookProfile);
                }
                else
                    throw new HttpException(404, "Missing Access Token");
        }

        public async Task<ActionResult> FB_TaggableFriends()
        {
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();

                var fb = new FacebookClient(access_token);
                dynamic myInfo = await fb.GetTaskAsync("me/taggable_friends".GraphAPICall(appsecret_proof));
                var friendsList = new List<FacebookFriendViewModel>();
                foreach (dynamic friend in myInfo.data)
                {

                    friendsList.Add(DynamicExtension.ToStatic<FacebookFriendViewModel>(friend));
                }

                return PartialView(friendsList);
            }
            else
                throw new HttpException(404, "Missing Access Token");
        }

        public async Task<ActionResult> FB_AdminPages()
        {
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();

                var fb = new FacebookClient(access_token);
                dynamic myPages = await fb.GetTaskAsync(
                    "me/accounts?fields=id, name, link, is_published, likes, talking_about_count"
                    .GraphAPICall(appsecret_proof));
                var pageList = new List<FacebookPageViewModel>();
                foreach (dynamic page in myPages.data)
                {

                    pageList.Add(DynamicExtension.ToStatic<FacebookPageViewModel>(page));
                }

                return PartialView(pageList);
            }
            else
                throw new HttpException(404, "Missing Access Token");
        }


        public async Task<ActionResult> FB_GetFeed()
        {
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();

                var fb = new FacebookClient(access_token);
       
                dynamic myFeed = await fb.GetTaskAsync(
                    ("me/feed?fields=id,from {{id, name, picture{{url}} }},story,picture,link,name,description," +
                    "message,type,created_time,likes,comments")
                    .GraphAPICall(appsecret_proof));
                var postList = new List<FacebookPostViewModel>();
                foreach (dynamic post in myFeed.data)
                {
                    postList.Add(DynamicExtension.ToStatic<FacebookPostViewModel>(post));
                }
                return PartialView(postList);
            }
            else
                throw new HttpException(404, "Missing Access Token");
        }

        #region Testing Action

        public async Task<ActionResult> FB_RevokeAccessToken()
        {
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();

                var fb = new FacebookClient(access_token);
                dynamic myFeed = await fb.DeleteTaskAsync(
                    "me/permissions".GraphAPICall(appsecret_proof));
                return RedirectToAction("Index", "Home");
            }
            else
                throw new HttpException(404, "Missing Access Token");
        }

        public Action FB_TestApiLimit()
        {
            throw new FacebookApiLimitException();
        }

        #endregion


        #region Permission Checking

        //private bool checkPermission()
        //{
        //    bool checkPermission = true;
        //    if (TempData["ProcessingPermissionRequest"] != null)
        //    {
        //        checkPermission = !((bool)TempData["ProcessingPermissionRequest"]);
        //    }
        //    return checkPermission;
        //}

        protected override Dictionary<string, FacebookPermissionRequest> GetRequiredPermissions()
        {
            Dictionary<string, FacebookPermissionRequest> RequiredPermissions =
                new Dictionary<string, FacebookPermissionRequest>();

            RequiredPermissions.Add
            ("read_stream",
                    new FacebookPermissionRequest
                    {
                        name = "View Your Posts",
                        description = "Provides the Social Manager with ability to present a listing of your Facebook Posts, Statuses, and Activities on the Posts Tab of the Profile Page.",
                        permision_scope_value = "read_stream",
                        requested = false
                    }
            );

            RequiredPermissions.Add
            ("manage_pages",
                    new FacebookPermissionRequest
                    {
                        name = "View Your Facebook Pages",
                        description = "Provides the Social Manager with ability to present a listing of Facebook Pages that you administer on the Pages Tab of the Profile Page.",
                        permision_scope_value = "manage_pages",
                        requested = false
                    }
            );

            RequiredPermissions.Add
            ("user_friends",
                    new FacebookPermissionRequest
                    {
                        name = "View Your Friends",
                        description = "Provides the Social Manager with ability to present a listing of your Friends to select for tagging purposes.",
                        permision_scope_value = "user_friends",
                        requested = false
                    }
            );
            return RequiredPermissions;

        }

        [HttpPost]
        public ActionResult RequestPermissions(
            string okButton, 
            string cancelButton, 
            string redirectURI,
            PermissionRequestViewModel acknowledgedPermissionRequest)
        {
            TempData["ProcessingPermissionRequest"] = true;
            if (okButton != null)
            {
                StringBuilder permission_scope = new StringBuilder();
                foreach (FacebookPermissionRequest permission in 
                    acknowledgedPermissionRequest.MissingPermissions.
                    Where(x => x.requested == true))
                {
                    permission_scope.Append(
                        string.Format("{0} ",
                        permission.permision_scope_value));
                }
                if (permission_scope.Length == 0)
                    return Redirect("Index");
                else
                {
                    var rerequestURL = base.AddPermissions(permission_scope.ToString(), redirectURI);
                    return Redirect(rerequestURL);
                }
            }
            else  //if(cancelButton != null)
            {
                return Redirect("Index");
            }
        }      

        #endregion
    }
}

SocialManager/Controllers/FacebookPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialManager.Models;
using SocialManager.Extensions;
using Facebook;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Configuration;
using Newtonsoft.Json;
using SocialManager.Filters;


namespace SocialManager.Controllers
{
    [Authorize]
    public class FacebookPostController : BaseController
    {
        // GET: FacebookPost
        [FacebookCheckPermission]
        public ActionResult Index()
        {
            #region Permission Check
            PermissionRequestViewModel permissionViewModel = base.GetMissingPermissions();
            if (permissionViewModel != null &&
                permissionViewModel.MissingPermissions.Count > 0)
            {
                return View("FB_RequestPermission", permissionViewModel);
            }
            #endregion

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> PostUserFeed(
            string Message,
            string Link,
            string Privacy,
            IList<string> FriendList)
        {
            #region Parameter Handling
            if (string.IsNullOrEmpty(Message))
                return Json("Cannot post a status without a message");
            //Default the Privacy to SELF if missing
            if (string.IsNullOrEmpty(Privacy))
                Privacy = "SELF";

            string linkParameter = string.Empty;
            if (!string.IsNullOrEmpty(Link))
            {
                linkParameter = string.Format("&link={0}", Link);
            }

            string FriendTagList = string.Empty;
            if (FriendList != null)
            {
                FriendTagList = string.Format("&place=155021662189&tags={0}",
                                string.Join(",", FriendList));
            }
            #endregion

            #region Facebook Graph API Post to User Feed
            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();
                var fb = new FacebookClient(access_token);

                #region Post
                dynamic myInfo = await fb.PostTaskAsync(
                    (string.Format("me/feed?message={0}{1}{2}",
                                    Message,
                                    linkParameter,
                                    FriendTagList) +
                                    "&privacy={{'value':'" + Privacy + "'}}").GraphAPICall(appsecret_proof), null);
                #endregion

                return Json("Status update has been succcessfully posted.");

            }
            else
                throw new HttpException(404, "Missing Access Token");
            #endregion
        }


        protected override Dictionary<string, FacebookPermissionRequest> GetRequiredPermissions()
        {
            Dictionary<string, FacebookPermissionRequest> RequiredPermissions =
                new Dictionary<string, FacebookPermissionRequest>();

            RequiredPermissions.Add
            ("publish_actions",
                    new FacebookPermissionRequest
                    {
                        name = "Posting",
                        description = "Provides the Social Manager with ability to add a new post to your Facebook news feed, page feed, event feed or group feed.",
                        permision_scope_value = "publish_actions",
                        requested = false
                    }
            );

            RequiredPermissions.Add
            ("user_friends",
                    new FacebookPermissionRequest
                    {
                        name = "View Your Friends",
                        description = "Provides the Social Manager with ability to present a listing of your Friends to select for tagging with your post.",
                        permision_scope_value = "user_friends",
                        requested = false
                    }
            );
            return RequiredPermissions;

        }

    }
}

SocialManager/Views/FacebookPost/Index.cshtml
<div class="row">
    <div class="col-md-8 col-md-offset-1">
        @using (Ajax.BeginForm("PostUserFeed", "FacebookPost", null,
                new AjaxOptions
                {
                    OnFailure = "handleError(xhr,'Taggable_Friends')",
                    HttpMethod = "Post",
                    UpdateTargetId = "Post_ResponseDiv",
                    LoadingElementId = "divPostingWaitImage",
                    InsertionMode = InsertionMode.Replace
                },
                new
                {
                    id = "Status_Post_Form",
                    @class = "form",
                    role = "form"
                }))
        {
            <div id="divPostingWaitImage" style="display:none;" class="text-center">
                <img src="~/images/loader.gif" />
            </div>
            <h4><span class="text-info">Update Your Status</span></h4>
            <div class="well">
                <div class="col-md-12">
                    <div class="form-group">

                        @* Status Message*@
                        <textarea name="Message"
                                  class="form-control"
                                  rows="3"
                                  style="max-width:100%;"
                                  placeholder="What's on your mind?"></textarea>
                    </div>
                    <div class="form-group">
                        @* LINK URL *@
                        <div class="input-group">
                            <div class="input-group-addon glyphicon glyphicon-globe"></div>
                            <input type="text" class="form-control" name="Link" 
                                   placeholder="Enter URL link...">
                        </div>
                    </div>
                </div>
                @* Privacy Input - Hidden*@
                <input name="Privacy" type="hidden" value="EVERYONE" />
                @* Tagged List of Friends - Hidden*@
                <div id="SelectedFriendListDiv" class="form-inline" style="display:none;">
                    <span class="text-muted">with&nbsp;</span>
                    <ul id="SelectedFriendList" class="list-group"></ul>

                </div>
            </div>
            <!-- Footer Row Action buttons: Tag Friends, Privacy, and Post-->
            <div class="form-group input-group">
                <div class="input-group">
                    <button type="button" class="btn" onclick="ShowTaggableFriendsDialog();">
                        <span class="glyphicon glyphicon-plus"></span>
                        <span class="glyphicon glyphicon-user"></span>
                    </button>
                    <div class="btn-group">
                        <button id="dropdownMenuPermission"
                                class="btn dropdown-toggle"
                                data-toggle="dropdown"
                                type="button">
                            Public
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li role="presentation">
                                <a role="menuitem" tabindex="-1" href="#" 
                                   data-privacy="EVERYONE">Public</a>
                            </li>
                            <li role="presentation">
                                <a role="menuitem" tabindex="-1" href="#" 
                                   data-privacy="ALL_FRIENDS">All Friends</a>
                            </li>
                            <li role="presentation">
                                <a role="menuitem" tabindex="-1" href="#" 
                                   data-privacy="FRIENDS_OF_FRIENDS">Friends of Friends</a>
                            </li>
                            <li role="presentation">
                                <a role="menuitem" tabindex="-1" href="#" 
                                   data-privacy="SELF">Only Me</a>
                            </li>
                        </ul>
                    </div>
                    <button type="submit" class="btn btn-primary">Post</button>
                </div>
            </div>
            <div id="Post_ResponseDiv" class="form-group text-success">
                <!-- Status Message Post Results goes here-->
            </div>
        }
    </div>
</div>

<!-- Taggable Friends Modal Dialog -->
<div class="modal" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Who are you with?</h4>
            </div>
            <div class="modal-body">
                @using (Ajax.BeginForm("FB_TaggableFriends", "Facebook", null,
                                    new AjaxOptions
                                    {
                                        OnFailure = "handleError(xhr,'Taggable_Friends')",
                                        HttpMethod = "Get",
                                        UpdateTargetId = "Taggable_Friends",
                                        LoadingElementId = "divLoadingTaggableFriends",
                                        InsertionMode = InsertionMode.Replace
                                    },
                                    new
                                    {
                                        id = "Taggable_Friends_Form"
                                    }))
                {
                    <div id="divLoadingTaggableFriends" style="display:none;" class="text-center">
                        <img src="~/images/loader.gif" />
                    </div>

                }
                <div id="Taggable_Friends"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" 
                        data-dismiss="modal" onclick="ApplySelectedFriends();">Apply</button>
                <button type="button" class="btn btn-default" 
                        data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryajax")
    <script type="text/javascript">
        wireupPrivacyDropDownMenu();

        function ShowTaggableFriendsDialog() {
            $("#Taggable_Friends").empty();
            $("#Taggable_Friends_Form").submit();
            $("#myModal").modal("show")
            return false;
        }

        function ApplySelectedFriends() {
            $("#SelectedFriendList").empty();
            var selectedCount = 0;
            $("input[name='Chk_SelectTaggableFriend']:checked").each(function () {
                selectedCount++;
                $("#SelectedFriendList").append(
                    "<li id='" + this.id +
                           "' class='list-group-item'>" +
                        "<img class='img-thumbnail' src='" +
                             this.attributes['data-imageurl'].value +
                          "'/>" + this.attributes['data-friendname'].value +
                        "<button type='button' class='btn btn-sm' " +
                        "onclick='RemoveSelectedFriend(\"" + this.id + "\");'>" +
                            "<span class='glyphicon glyphicon-remove'></span></button>" +
                     "</li>");
                $("#SelectedFriendListDiv").append(
                    "<input type='hidden' name='FriendList' value='" +
                    this.id + "' id='FriendList_" + this.id + "' />");
            });
            if (selectedCount > 0) {
                $("#SelectedFriendListDiv").show();
            }
            else {
                $("#SelectedFriendListDiv").hide();
            }
            return true;
        }

        function RemoveSelectedFriend(item) {
            $("#" + item).remove();
            $("#FriendList_" + item).remove();
            if ($("#SelectedFriendList > li").length == 0) {
                $("#SelectedFriendListDiv").hide();
            }
        }
    </script>
}